### ISSUE TITLE
getting async error when trying to run the code...

### ISSUE THREAD

**Issue by bhanusah** [Microsoft/LUIS-Samples#122]
var addUtterance = async (config) => {
                         ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

**Comment by v-geberr** [comment]
What version of node is on the box?

**Comment by diberry** [comment]
I believe the issue is that the code is using an feature that your version of Node.js does not support. If you feel this is incorrect, please reopen the issue with more information.
